#!/bin/bash
PWD=`pwd`

help()
{
    echo "runDevServer"
    echo "USAGE: runDevServer [OPTIONS]"
    echo ""
    echo "OPTION:"
    echo " help   display help"
    echo " migrate  makes migrations for the server"
    echo " run with no options to start the server"
    echo ""
    exit 2
}

cd source/foodPortal/

if [[ $1 = "help" || $1 = "-h" ]]
then
    help
elif [[ $1 = "migrate" ]]
then
    python3 manage.py makemigrations
    python3 manage.py migrate
else
    python3 manage.py runserver
fi

