#!/bin/bash
IGNORE=" ! -wholename *.svn* ! -wholename *.git* ! -wholename .*log* ! -wholename .*Log* ! -wholename static"

PWD=`pwd`

help()
{
    echo "djangoTags"
    echo "USAGE: djangoTags"
    echo ""
    echo "OPTION:"
    echo " --help   display help"
    echo " --test   shows the list of target tags directories"
    echo " --init   generate tags to all subfolders besides ignored oens set in script"
    echo " --ask    ask for confirmation for tags generation"
    echo " --clean  clean all the tags files"
    echo " --show   locate all the tags files"
    echo ""
    exit 2
}

ask()
{
    read -p "ctags * $1  [y/n] " ANS
    if [[ $ANS = "y" || $ANS = "Y" ]]
    then
        gentags $1
    fi
}

info()
{
    echo ""
    echo "run 'gentags --init' without quotes at your base project folder"
    echo "paste the lines below to your ~/.vimrc"
    echo ":nmap ,t :!(cd %:p:h;ctags *)&"
    echo ":set tags=./tags,./../tags,./../../tags,./../../../tags,tags"
    echo ""
}

if [[ $1 = "--help" || $1 = "-h" ]]
then
    helpme
elif [[ $1 = "--test" ]]
then
    find . -type d $IGNORE
elif [[ $1 = "--init" ]]
then
    ctags -R --file-scope=no --fields=+l --languages=python --python-kinds=-iv -f ./tags $(python3 -c "import os, sys; print(' '.join('{}'.format(d) for d in sys.path if os.path.isdir(d)))") 
    find . -type d $IGNORE -exec `basename $0` {} \;
elif [[ $1 = "--ask" ]]
then
    ctags -R --file-scope=no --fields=+l --languages=python --python-kinds=-iv -f ./tags $(python3 -c "import os, sys; print(' '.join('{}'.format(d) for d in sys.path if os.path.isdir(d)))") 
    find . -type d $IGNORE -exec `basename $0` --ask2 {} \;
elif [[ $1 = "--ask2" ]]
then
    ask $2
elif [[ $1 = "--clean" ]]
then
    find . -name "tags" -exec rm {} \;
elif [[ $1 = "--show" ]]
then
    find . -name "tags"
else
    TARGET=""
    if [[ $1 = "." ]]
    then
        TARGET=$PWD
    else
        TARGET=$1
    fi
    cd $TARGET
    ctags *
    find * -type d -prune -print | ctags -aR --file-scope=no -L-
fi

